version: '3'

services:
  traderbot_webapp:
    container_name: traderbot_webapp
    build:
      context: .
      dockerfile: ./ci/Dockerfile
    restart: always
    ports:
      - "8881:8881"
    # command: quasar dev
    stdin_open: true
    tty: true
    environment:
      #CHOKIDAR_USEPOLLING: true
      VIRTUAL_HOST: app.tradingbotservices.com
      LETSENCRYPT_HOST: app.tradingbotservices.com
      LETSENCRYPT_EMAIL: rogerzavarce@gmail.com
    networks:
      default:
        ipv4_address: 172.18.0.100

networks:
  default:
    external:
      name: tradingbot
