version: '3'

services:
  traderbot_webapp:
    container_name: traderbot_webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"
    # command: quasar dev
    stdin_open: true
    tty: true
    environment:
      #CHOKIDAR_USEPOLLING: true
      VIRTUAL_HOST: app.tradingbotservices.com
      LETSENCRYPT_HOST: app.tradingbotservices.com
      LETSENCRYPT_EMAIL: rogerzavarce@gmail.com

networks:
  default:
    external:
      name: tradingbot
